[package]
name = "omp-switch"
version = "0.1.5"
description = "OMP 供应商/模型配置管理器"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "image-png"] }
tauri-plugin-shell = "2"

[lib]
name = "omp_switch_lib"
crate-type = ["staticlib", "cdylib", "rlib"]
